apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
  labels:
    app: portal
    provider: szyjian
    group: com.szyjian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
      provider: szyjian
      group: com.szyjian
  template:
    metadata:
      labels:
        app: portal
        provider: szyjian
        group: com.szyjian
    spec:
      containers:
      - name: portal
        image: registry.apps.dev.szyjian.com/portal:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
      imagePullSecrets:
      - name: registry-auth-secret
---
apiVersion: v1
kind: Service
metadata:
  name: portal
  labels:
    app: portal
spec:
  selector:
    app: portal
    provider: szyjian
    group: com.szyjian
  #type: ClusterIP
  type: NodePort
  ports:
  - name: http
    nodePort: 30020
    port: 80
    targetPort: 80
